package net.redbear.taskmap;

/**
 * Created by Dong on 16/1/14.
 */
public enum Step {
    WIFI_SUPPORT,
    WIFI_NOT_SUPPORT,
    WIFI_ON,
    WIFI_NOT_ON,
    AP_IS_PROVISION_STATE,
    AP_IS_NOT_PROVISION_STATE,
    BLE_SUPPORT,
    BLE_NOT_SUPPORT,
    BLE_IS_ON,
    BLE_IS_NOT_ON,
    BLE_SCAN,
    BLE_CONTROLLER,
    BLE_PROVISION,
    BLE_PROVISION_SCAN,
    BLE_PROVISION_SEND_PASSWORD,
    BLE_PROVISION_FINISH,
    WIFI_MDNS_SCAN,
    WIFI_CONTROLLER,
    WIFI_PROVISION,
    WIFI_PROVISION_SCAN,
    WIFI_PROVISION_SEND_PASSWORD,
    WIFI_PROVISION_FINISH,
}
